version: "3.9"
services:
  api:
    container_name: various-app-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - various-app-network
  db:
    container_name: various-app-db
    image: postgres:14.5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./backend/persist/postgres:/var/lib/postgresql/data
      - ./backend/DDL:/docker-entrypoint-initdb.d
    networks:
      - various-app-network
  pgadmin:
    container_name: various-app-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - ./backend/persist/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - various-app-network
  localstack:
    container_name: various-app-localstack
    build:
      context: ./backend
      dockerfile: docker/localstack/Dockerfile
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_SOCK=/var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./backend/docker/localstack:/docker-entrypoint-initaws.d:ro
      - ./backend/persist/localstack/data:/var/lib/localstack/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4566:4566
    networks:
      - various-app-network
networks:
  various-app-network:
    driver: bridge
